import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { SiteHeader } from "@/components/site-header";
import { SearchProvider } from "@/context/SearchContext";
import { LayoutWrapper } from "@/components/layout/LayoutWrapper";
import { Providers } from "@/components/Providers";
import { SessionProvider } from "next-auth/react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* ---------------------by own--------------------------- */}
          {/* <SidebarProvider>
            <SidebarInset className="relative">
              <SearchProvider>
                <div className="fixed top-0 left-0 right-0 z-50 bg-red-500">
                  <SiteHeader />
                </div>
                <main className="pt-[120px] px-4 lg:px-20">{children}</main>
              </SearchProvider>
            </SidebarInset>
          </SidebarProvider> */}

          {/* ------------------------by Layout--------------------------------- */}
          {/* <SidebarProvider>
            <SidebarInset className="relative">
              <SearchProvider>
                <LayoutWrapper>{children}</LayoutWrapper>
              </SearchProvider>
            </SidebarInset>
          </SidebarProvider> */}

          {/* --------------------------by Provider in components------------------------------- */}

          <Providers>
            <LayoutWrapper>{children}</LayoutWrapper>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
